export const container: string;
export const icons: string;
export const search: string;
export const searchIcon: string;
export const show: string;
export const hide: string;
export const wrapper: string;
export const bigButton: string;
export const smallButton: string;
