export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export type RECEIVE_ORDERS = typeof RECEIVE_ORDERS;

export const RECEIVE_PAYINFO = 'RECEIVE_PAYINFO';
export type RECEIVE_PAYINFO = typeof RECEIVE_PAYINFO;

export const RECEIVE_INCOME_RECORD = 'RECEIVE_INCOME_RECORD';
export type RECEIVE_INCOME_RECORD = typeof RECEIVE_INCOME_RECORD;