export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export type RECEIVE_ORDERS = typeof RECEIVE_ORDERS;

export const RECEIVE_PAYINFO = 'RECEIVE_PAYINFO';
export type RECEIVE_PAYINFO = typeof RECEIVE_PAYINFO;

export const RECEIVE_INCOME_RECORD = 'RECEIVE_INCOME_RECORD';
export type RECEIVE_INCOME_RECORD = typeof RECEIVE_INCOME_RECORD;

export const SET_SELECTED_ADDRESS = 'SET_SELECTED_ADDRESS';
export type SET_SELECTED_ADDRESS = typeof SET_SELECTED_ADDRESS;

export const SET_SELECTED_GASHAPONS = 'SET_SELECTED_GASHAPONS';
export type SET_SELECTED_GASHAPONS = typeof SET_SELECTED_GASHAPONS;

export const RECEIVE_PACKAGE_LOCATION = 'RECEIVE_PACKAGE_LOCATION';
export type RECEIVE_PACKAGE_LOCATION = typeof RECEIVE_PACKAGE_LOCATION;