export const RECEIVE_COUPONS = 'RECEIVE_COUPONS';
export type RECEIVE_COUPONS = typeof RECEIVE_COUPONS;

export const LOADING_COUPONS_STATUS = 'LOADING_COUPONS_STATUS';
export type LOADING_COUPONS_STATUS = typeof LOADING_COUPONS_STATUS;

export const LAST_LOAD_COUPONS_TYPE = 'LAST_LOAD_COUPONS_TYPE';
export type LAST_LOAD_COUPONS_TYPE = typeof LAST_LOAD_COUPONS_TYPE;