export const RECEIVE_DISCOUNT = 'RECEIVE_DISCOUNT';
export type RECEIVE_DISCOUNT = typeof RECEIVE_DISCOUNT;

export const RECEIVE_HOME_DISOUNT = 'RECEIVE_HOME_DISOUNT';
export type RECEIVE_HOME_DISOUNT = typeof RECEIVE_HOME_DISOUNT;