
export const RECEIVE_GASHAPON = 'RECEIVE_GASHAPON';
export type RECEIVE_GASHAPON = typeof RECEIVE_GASHAPON;

export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
export type CHANGE_LOADING_STATUS = typeof CHANGE_LOADING_STATUS;

export const RECEIVE_GAHSAPON_COMMENTS = 'RECEIVE_GAHSAPON_COMMENTS';
export type RECEIVE_GAHSAPON_COMMENTS = typeof RECEIVE_GAHSAPON_COMMENTS;

export const RECEIVE_GASHAPON_SHOWS = 'RECEIVE_GASHAPON_SHOWS';
export type RECEIVE_GASHAPON_SHOWS = typeof RECEIVE_GASHAPON_SHOWS;
