
export const RECEIVE_GASHAPON = 'RECEIVE_GASHAPON';
export type RECEIVE_GASHAPON = typeof RECEIVE_GASHAPON;

export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
export type CHANGE_LOADING_STATUS = typeof CHANGE_LOADING_STATUS;