export const RECEIVE_HOME_USERDATA = 'RECEIVE_HOME_USERDATA';
export type RECEIVE_HOME_USERDATA = typeof RECEIVE_HOME_USERDATA;

export const RECEIVE_HOME_COLLECT = 'RECEIVE_HOME_COLLECT';
export type RECEIVE_HOME_COLLECT = typeof RECEIVE_HOME_COLLECT;