export const RECEIVE_HOME_USERDATA = 'RECEIVE_HOME_USERDATA';
export type RECEIVE_HOME_USERDATA = typeof RECEIVE_HOME_USERDATA;

export const RECEIVE_HOME_COLLECT = 'RECEIVE_HOME_COLLECT';
export type RECEIVE_HOME_COLLECT = typeof RECEIVE_HOME_COLLECT;

export const RECEIVE_CODE = 'RECEIVE_CODE';
export type RECEIVE_CODE = typeof RECEIVE_CODE;

export const RECEIVE_OREDER_COUNT = 'RECEIVE_OREDER_COUNT';
export type RECEIVE_OREDER_COUNT = typeof RECEIVE_OREDER_COUNT;