export const INCREMENT_NUMBER = 'INCREMENT_NUMBER';
export type INCREMENT_NUMBER = typeof INCREMENT_NUMBER;

export const DECREMENT_NUMBER = 'DECREMENT_NUMBER';
export type DECREMENT_NUMBER = typeof DECREMENT_NUMBER;

export const INCREMENT_DEMO = 'INCREMENT_DEMO';
export type INCREMENT_DEMO = typeof INCREMENT_DEMO;

export const DECREMENT_DEMO = 'DECREMENT_DEMO';
export type DECREMENT_DEMO = typeof DECREMENT_DEMO;

export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export type RECEIVE_PRODUCTS = typeof RECEIVE_PRODUCTS;

export const RECEIVE_MATCHES = 'RECEIVE_MATCHES';
export type RECEIVE_MATCHES = typeof RECEIVE_MATCHES;