
export const RECEIVE_INVENTORY = 'RECEIVE_INVENTORY';
export type RECEIVE_INVENTORY = typeof RECEIVE_INVENTORY;

export const LOADING_INVENTORY_STATUS = 'LOADING_INVENTORY_STATUS';
export type LOADING_INVENTORY_STATUS = typeof LOADING_INVENTORY_STATUS;

export const LAST_LOAD_INVENTORY_GENRE = 'LAST_LOAD_INVENTORY_GENRE';
export type LAST_LOAD_INVENTORY_GENRE = typeof LAST_LOAD_INVENTORY_GENRE;