
export const RECEIVE_MAIN_GAHSAPONS = 'RECEIVE_MAIN_GAHSAPONS';
export type RECEIVE_MAIN_GAHSAPONS = typeof RECEIVE_MAIN_GAHSAPONS;

export const LAST_LOAD_GASHAPONS_GENRE = 'LAST_LOAD_GASHAPONS_GENRE';
export type LAST_LOAD_GASHAPONS_GENRE = typeof LAST_LOAD_GASHAPONS_GENRE;

export const LAST_LOAD_GASHAPONS_TOPIC = 'LAST_LOAD_GASHAPONS_TOPIC';
export type LAST_LOAD_GASHAPONS_TOPIC = typeof LAST_LOAD_GASHAPONS_TOPIC;

export const LAST_LOAD_GASHAPONS_WORD = 'LAST_LOAD_GASHAPONS_WORD';
export type LAST_LOAD_GASHAPONS_WORD = typeof LAST_LOAD_GASHAPONS_WORD;

export const LOADING_GASHAPONS = 'LOADING_GASHAPONS';
export type LOADING_GASHAPONS = typeof LOADING_GASHAPONS;

export const RECEIVE_MAIN_BANNERS = 'RECEIVE_MAIN_BANNERS';
export type RECEIVE_MAIN_BANNERS = typeof RECEIVE_MAIN_BANNERS;

export const RECEIVE_BANNERS_BY_GENRE = 'RECEIVE_BANNERS_BY_GENRE';
export type RECEIVE_BANNERS_BY_GENRE = typeof RECEIVE_BANNERS_BY_GENRE;

export const RECEIVE_BANNERS_BY_TOPIC = 'RECEIVE_BANNERS_BY_TOPIC';
export type RECEIVE_BANNERS_BY_TOPIC = typeof RECEIVE_BANNERS_BY_TOPIC;

export const RECEIVE_GENRES = 'RECEIVE_GENRES';
export type RECEIVE_GENRES = typeof RECEIVE_GENRES;

export const RECEIVE_TOPICS = 'RECEIVE_TOPICS';
export type RECEIVE_TOPICS = typeof RECEIVE_TOPICS;

export const RECEIVE_HOT_SEARCH_WORDS = 'RECEIVE_HOT_SEARCH_WORDS';
export type RECEIVE_HOT_SEARCH_WORDS = typeof RECEIVE_HOT_SEARCH_WORDS;

export const RECEIVE_MAIN_DATA = 'RECEIVE_MAIN_DATA';
export type RECEIVE_MAIN_DATA = typeof RECEIVE_MAIN_DATA;