
export const RECEIVE_MAIN_GAHSAPONS = 'RECEIVE_MAIN_GAHSAPONS';
export type RECEIVE_MAIN_GAHSAPONS = typeof RECEIVE_MAIN_GAHSAPONS;

export const RECEIVE_MAIN_BANNERS = 'RECEIVE_MAIN_BANNERS';
export type RECEIVE_MAIN_BANNERS= typeof RECEIVE_MAIN_BANNERS;