export const RECEIVE_MAIN_SWIPER_IMAGES = 'RECEIVE_MAIN_SWIPER_IMAGES';
export type RECEIVE_MAIN_SWIPER_IMAGES = typeof RECEIVE_MAIN_SWIPER_IMAGES;

export const RECEIVE_MAIN_NEW_MUSICS = 'RECEIVE_MAIN_NEW_MUSICS';
export type RECEIVE_MAIN_NEW_MUSICS = typeof RECEIVE_MAIN_NEW_MUSICS;

export const RECEIVE_MAIN_RECOMMEND_PLAYLIST = 'RECEIVE_MAIN_RECOMMEND_PLAYLIST';
export type RECEIVE_MAIN_RECOMMEND_PLAYLIST = typeof RECEIVE_MAIN_RECOMMEND_PLAYLIST;

export const RECEIVE_MAIN_RECOMMEND_TRIBE = 'RECEIVE_MAIN_RECOMMEND_TRIBE';
export type RECEIVE_MAIN_RECOMMEND_TRIBE = typeof RECEIVE_MAIN_RECOMMEND_TRIBE;