
export const RECEIVE_MAIN_GAHSAPONS = 'RECEIVE_MAIN_GAHSAPONS';
export type RECEIVE_MAIN_GAHSAPONS = typeof RECEIVE_MAIN_GAHSAPONS;

export const LAST_LOAD_GASHAPONS_GENRE = 'LAST_LOAD_GASHAPONS_GENRE';
export type LAST_LOAD_GASHAPONS_GENRE = typeof LAST_LOAD_GASHAPONS_GENRE;

export const LOADING_GASHAPONS = 'LOADING_GASHAPONS';
export type LOADING_GASHAPONS = typeof LOADING_GASHAPONS;

export const RECEIVE_MAIN_BANNERS = 'RECEIVE_MAIN_BANNERS';
export type RECEIVE_MAIN_BANNERS = typeof RECEIVE_MAIN_BANNERS;

export const RECEIVE_GENRES = 'RECEIVE_GENRES';
export type RECEIVE_GENRES = typeof RECEIVE_GENRES;