export const SHOW_SEARCH_MODAL = 'SHOW_SEARCH_MODAL';
export type SHOW_SEARCH_MODAL = typeof SHOW_SEARCH_MODAL;

export const HIDE_SEARCH_MODAL = 'HIDE_SEARCH_MODAL';
export type HIDE_SEARCH_MODAL = typeof HIDE_SEARCH_MODAL;

export const ADD_SEARCH_ITEM = 'ADD_SEARCH_ITEM';
export type ADD_SEARCH_ITEM = typeof ADD_SEARCH_ITEM;

export const EMPTY_SEARCH_ITEMS = 'EMPTY_SEARCH_ITEMS';
export type EMPTY_SEARCH_ITEMS = typeof EMPTY_SEARCH_ITEMS;
