export const container: string;
export const user: string;
export const menuItem: string;
export const set: string;
export const money: string;
export const menu: string;
export const utils: string;
export const data: string;
export const dataBanner: string;
