export const container: string;
export const bgimg: string;
export const title: string;
export const image: string;
export const tip: string;
export const button: string;
export const cover: string;
export const name: string;
export const item: string;
