export const container: string;
export const footer: string;
export const modify: string;
export const box: string;
export const item: string;
export const input: string;
export const title: string;
export const icon: string;
export const defaultText: string;
